#!/bin/bash
### Description: 这个脚本放置一些adb 的一些快捷命令
### Author: foree
### Date: 20151028
ADB_PATH=`which adb`

function fadb
{
    case "$1" in
        kill)
            if [ -z $2 ];then
                echo "Usages: fadb kill <keyword>"
            else
                $ADB_PATH shell kill -9 `adb shell ps |grep $2 |awk '{print $2}'`
            fi
            ;;
        push)
            if [ -z $2 ];then
                echo "Usages: fadb push <localfile>"
            else
                croot 2>&1 >/dev/null
                if [ $? -eq 0 ];then
                    adb remount
                    localfile=$2
                    localfile=${localfile#*/*/*/*/}
                    remotefile=${localfile%/*}
                    $ADB_PATH push $2 /$remotefile/
                    cd -
                else
                    echo " "
                    echo -e "\033[31m You Must run lunch first!!!\033[0m"
                    echo " "
                fi
            fi
            ;;

        *)
            $ADB_PATH $@
    esac
}
