#!/bin/bash
### Description: 这个脚本放置一些adb 的一些快捷命令
### Author: foree
### Date: 20151028

SOFT_DIR=$(dirname $(realpath $0))
source $SOFT_DIR/common.sh


function fadb
{
    TOPDIR=$(_gettopdir)

    if [ -z $TOPDIR ];then echo "Not Found Project Here !!";return 1 ;fi

    ADB_PATH=/usr/bin/adb
    case "$1" in
        kill)
            if [ -z $2 ];then
                echo "Usages: fadb kill <keyword>"
            else
                $ADB_PATH shell kill -9 `adb shell ps |grep $2 |awk '{print $2}'`
            fi
            ;;
        push)
            if [ -z $2 ];then
                echo "Usages: fadb push <localfile>"
            else
                cd $TOPDIR
                adb root
                adb remount
                localfile=$2
                localfile=${localfile#*/*/*/*/}
                remotefile=${localfile%/*}
                $ADB_PATH push $2 /$remotefile/
            fi
            ;;

        *)
            $ADB_PATH $@
    esac
}
fadb $@
