#!/bin/bash
### Description: repo 相关命令的封装
### Author: foree
### Date:20151204
SOFT_DIR=$(dirname $(realpath $0))

source $SOFT_DIR/common.sh

#使用repo sync -c -d 同步代码并加时间戳
function repo_sync
{
    local whattime
    local DEFAULT_BRANCH
    local TOPDIR=$(_getrepodir)

    if [ -z "$TOPDIR" ];then echo "Not Found Project Here !!";return 1 ;fi

    cd $TOPDIR

    if [ -f .repo/manifests/default.xml ];then
        pushd .repo/manifests
        DEFAULT_BRANCH=$(git br -r | head -n 1 |awk -F "/" '{print $3}' )
        popd
    else
        add_color_for_echo "default.xml not found !" >&2
        return 1
    fi
    whattime=`date +%Y_%m%d_%H%M`
    repo sync -c -d
    repo start ${DEFAULT_BRANCH}_${whattime} --all
}

#判断Android Project是否reference到其他地方
function is_reference()
{
    local alternate=".repo/manifests.git/objects/info/alternates"
    T=$(_gettopdir)
    if [ -f "$T/$alternate" ];then
        cat "$T/$alternate"
    else
        echo "No Reference"
    fi
}

#通过指定分支自动reference到某一目录
function repo_init()
{
    if [ "x$2" = "x-b" -a ! -z "$2" ];then
        repo init --reference=~/android/MZ-l1_base_mirror -u ssh://liming1@review.rnd.meizu.com:29999/platform/manifest -b "$3"
    else
        echo
        add_color_for_echo "Usage: frepo init -b branch_name"
        echo
    fi

}

function main()
{

    option=$1

    if [ $# -ge 1 -a ! -z "$option" ];then
        case "$option" in
            init)
                repo_init $@
                ;;
            sync)
                repo_sync
                ;;
            reference)
                is_reference
                ;;
            *)
                repo $@
                ;;
        esac
    else
        echo
        add_color_for_echo "Usage: frepo [init|sync|reference]"
        echo
    fi
}
main $@
