#!/bin/bash
### Description: 用于更新与卸载foree-tools
### Author:foree
### Date:20151205

SOFT_DIR=$(dirname $(realpath $0))
source $SOFT_DIR/common.sh
flog -D "SOFT_DIR is $SOFT_DIR"

option=$1
case $option in
    -C)
        flog -I "uninstall foree-tools"
        $SOFT_DIR/uninstall.sh
        ;;
    -u)
        flog -I "update server project list"
        $SOFT_DIR/update.sh -u
        ;;
    -a)
        flog -I "update foree-tools and server project list"
        $SOFT_DIR/update.sh -a
        ;;
    -r)
        cd $SOFT_DIR
        grep "/" SERVER_* -H |sort -t'/' -k 2
        cd - >/dev/null
        ;;
    *)
        flog -W "Usage: ftools [-C|-u|-r]"
        echo ""
        echo "  -C Uninstall foree-tools"
        echo "  -u Update server project list"
        echo "  -a Update foree-tools and server project list"
        echo "  -r Resolve project"
        echo ""
        ;;
esac
