#!/bin/bash
### Description: 用于更新与卸载foree-tools
### Author:foree
### Date:20151205

SOFT_DIR=$(dirname $(realpath $0))
source $SOFT_DIR/common.sh
flog -D "SOFT_DIR is $SOFT_DIR"

option=$1
case $option in
    -C)
        flog -I "uninstall foree-tools"
        $SOFT_DIR/uninstall.sh
        ;;
    -u)
        flog -I "update foree-tools"
        $SOFT_DIR/update.sh -u
        ;;
    *)
        flog -W "Usage: ftools [-C|-u]"
        ;;
esac
