#!/bin/bash
SERVER_IP_1=172.16.132.36
SERVER_IP_2=172.16.132.38
LOGIN_IP=$SERVER_IP_1
PROJECT_LIST=~/bin/project_list
PROJECT_CONF=~/.config/foree-tools/foree-tools.conf
DO_CHOICE="true"
function server_info
{
    echo "which server you want to login ?"
    echo "1.IP 172.16.132.36"
    echo -n "   bringup:"
    echo -e "\033[33m M76_flyme5 \033[0m"
    echo -n "   dailybuild: "
    echo -e "\033[33m M75_base, M76_base, M85_base\033[0m"
    echo " 2.IP 172.16.132.38"
    echo -n "   bringup:"
    echo -e "\033[33m M71_flyme5, MA01C_base \033[0m"
    echo -n "   dailybuild:"
    echo -e "\033[33m M71C_base, M85-l1_base, M86_base, M86_flyme5, M88_base, MA01_base\033[0m"
}
function first_login
{
    if [ "$IF_FIRST_LOGIN"x = "true"x ] ;then 
        scp bringup@"$LOGIN_IP":~/.ssh/authorized_keys .
        cat ~/.ssh/id_rsa.pub >> authorized_keys
        scp authorized_keys bringup@"$LOGIN_IP":~/.ssh/
        echo "first login"
        sed -i '1,5s/true/false/' $0
    fi
}

function ssh_bringup
{
    if [ ! -z "$1" ];then
        search_result=$( grep -i "$1" $PROJECT_CONF |awk -F : '{print $1}')
        if [ ! -z "$search_result" ];then
            if [ "$search_result"x = "SERVER_1"x ];then
                DO_CHOICE="false"
                LOGIN_IP="$SERVER_IP_1"
                echo "项目在 $search_result"
            elif [ "$search_result"x = "SERVER_IP_2"x ];then
                DO_CHOICE="false"
                LOGIN_IP="$SERVER_IP_2"
                echo "项目在 $search_result"
            else
                echo "多个服务器同时存在$1 项目，请选择"
            fi
        else
            echo "没有指定的项目存在,请在以下项目中选择"
        fi
    fi

    if [ "$DO_CHOICE"x = "true"x ];then
        server_info
        echo -n "<1/2>? "
        read SELECTION

        case "$SELECTION" in 
            2)
                LOGIN_IP="$SERVER_IP_2"
                ;;
            *)
                LOGIN_IP="$SERVER_IP_1"
                ;;
        esac
    fi

    ssh-copy-id -i ~/.ssh/id_rsa.pub bringup@$LOGIN_IP 2>&1 > /dev/null
    ssh bringup@$LOGIN_IP
}
